global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'owasp-lab'
    metrics_path: /metrics
    static_configs:
      - targets: ['lab:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
